# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40c77e8e97ffbc1c37306e5d172753470a16646cb6463e0529836d38be46e343e88cc3d5584f380988d2c008f63040fadc8926746c94b2296d67bf7b86b248f1

test:
  secret_key_base: c4d652a57d00c0b2cb1eff6eace9b17e706ebc94433a82f78f768efef293fbdb0c3a53fa2313a1b45f20ce0fefdbd3bd470c3d5570ce52914ad9f646b1711adf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
